[project]
name = "personal-finance-assistant"
version = "0.1.0"
description = "Final project for the Introduction to Python course, applying Python programming to have a personal finance assistant."
readme = "README.md"
authors = [
    { name = "Your Name", email = "sed.mirzaee@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
personal-finance-assistant = "personal_finance_assistant:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
