[project]
name = "personal-finance-assistant"
version = "0.1.0"
description = "Final project for the Introduction to Python course. A simple tool to track transactions, keep an account balance, and get simple savings/investment suggestions."
readme = "README.md"
authors = [
    { name = "Sedigheh Mirzaei", email = "sed.mirzaee@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "jupyterlab>=4.6.3",
    "numpy>=2.5.3",
]

[project.scripts]
personal-finance-assistant = "personal_finance_assistant.cli:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "pip>=26.2.1",
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[project.urls]
Homepage = "https://github.com/sed-mirzaee/Personal-Finance-Assistant"
